const menuItems = [
  {
    id: 1,
    category: "News",
    items: [
      "UK",
      "Coronavirus",
      "Climate",
      "Crisis",
      "Environment",
      "Tech",
      "Business",
      "Science",
      "Global Development",
      "Football",
    ],
  },
  {
    id: 2,
    category: "Magazine",
    items: [
      "Features",
      "Opinion",
      "Analysis",
      "Interviews",
      "Reviews",
      "Profiles",
      "Essays",
      "Lifestyle",
      "Fashion",
      "Travel",
    ],
  },
  {
    id: 3,
    category: "Sport",
    items: [
      "Football",
      "Cricket",
      "Rugby",
      "Tennis",
      "Athletics",
      "Golf",
      "Motorsport",
      "Cycling",
      "Boxing",
      "Basketball",
    ],
  },
  {
    id: 4,
    category: "Culture",
    items: [
      "Art",
      "Books",
      "Music",
      "Film",
      "Television",
      "Theatre",
      "Dance",
      "Opera",
      "Classical",
      "Photography",
    ],
  },
  {
    id: 5,
    category: "Lifestyle",
    items: [
      "Food & Drink",
      "Health & Fitness",
      "Relationships",
      "Travel",
      "Home & Garden",
      "Fashion",
      "Beauty",
      "Family",
      "Work & Career",
      "Money",
    ],
  },
];

export default menuItems;
